### PR TITLE
Test with actual glossary entry fails

### PR DESCRIPTION
**Pull request by gvwilson**
This new test is taken from the [novice SQL lesson](https://github.com/swcarpentry/sql-novice-survey).  It appears to be correctly formatted, but the validator complains.  Several other tests fail when the validator is run in the `core` branch, but that's a separate issue.

### CODE REVIEW

**Comment by gvwilson** [comment]
@r-gaia-cs can you please have a look as well?

**Comment by abought** [comment]
Thanks for highlighting this. +1 to adding this unit test. We should also have a unit test for footnote links.

Both these issues appear related: Pandoc offers extensions to markdown. Currently we are using the CommonMark parser, which does not provide these features. The solution is to move to Pandoc as the internal AST/parser used by the validator. Plan is to pick up with Raniere's work on this starting next Tuesday.

Per tests failing in core: a few tests (sample files and link functionality) depend on assets in `gh-pages`. These tests have been demonstrably useful, but should be broken out as a separate test suite to assist with development on `core`. Any commits cleaning up tests would be welcomed.

**Comment by rgaiacs** [comment]
Here is one explanation why this happens:

```
>>> import CommonMark
>>> parser = CommonMark.DocParser()
>>> ast = parser.parse("""atomic                                                                                
... :   Describes                                                                                               
...     a value""")   
>>> ast.children[0].strings
['atomic', ':   Describes', 'a value']
```

CommonMark remove white spaces at the begin and at the end of each line. This means that there is no way to us tracking the correct indentation at glossary.

**Comment by gvwilson** [comment]
||

> CommonMark remove white spaces at the begin and at the end of each 
> line. This means that there is no way to us tracking the correct 
> indentation at glossary.
> 
> Gaaaaahhhh.  OK, what's the workaround?

**Comment by gvwilson** [comment]
>  *
> 
> ```
> *Tests failing in core* : a few tests (sample files and link
> functionality) depend on assets in |gh-pages|. These tests have
> been demonstrably useful, but should be broken out as a separate
> test suite to assist with development on |core|. Any commits
> cleaning up tests would be welcomed.
> ```
> 
> One option is to leave test_check.py in 'core' with all _internal_ 
> document checks, then add a second test file to gh-pages for _external_ 
> checks.  If the first is called test_check.py, what should the second be 
> called?

**Comment by rgaiacs** [comment]
> > CommonMark remove white spaces at the begin and at the end of each
> > line. This means that there is no way to us tracking the correct
> > indentation at glossary.
> 
> Gaaaaahhhh.  OK, what's the workaround?

Move to Pandoc.  I will work at #139 for the rest of the day.

> > _Tests failing in core_ : a few tests (sample files and link
> > functionality) depend on assets in |gh-pages|. These tests have
> > been demonstrably useful, but should be broken out as a separate
> > test suite to assist with development on |core|. Any commits
> > cleaning up tests would be welcomed.
> 
> One option is to leave test_check.py in 'core' with all _internal_
> document checks, then add a second test file to gh-pages for _external_
> checks.  If the first is called test_check.py, what should the second be
> called?

+1 to this approach. Maybe use `test_integration_check.py`?

@abought Could you try to split `test_check.py`?

**Comment by abought** [comment]
> @abought Could you try to split test_check.py?

Indeed. This and #139 are on my radar. Need to clear some work stuff but I'll aim for Tuesday to work on this.

**Comment by rgaiacs** [comment]
@gvwilson Using swcarpentry/sql-novice-survey@dbd1d59 and checking with #181

```
ERROR:root:In /tmp/sql/instructors.md: Line 56 contains FIXME, indicating work in progress
ERROR:root:In /tmp/sql/instructors.md: Line 60 contains FIXME, indicating work in progress
ERROR:root:In /tmp/sql/instructors.md: Line 64 contains FIXME, indicating work in progress
ERROR:root:In /tmp/sql/instructors.md: Line 68 contains FIXME, indicating work in progress
ERROR:root:In /tmp/sql/instructors.md: Line 72 contains FIXME, indicating work in progress
ERROR:root:In /tmp/sql/instructors.md: Line 76 contains FIXME, indicating work in progress
ERROR:root:In /tmp/sql/instructors.md: Line 80 contains FIXME, indicating work in progress
ERROR:root:In /tmp/sql/instructors.md: Line 84 contains FIXME, indicating work in progress
ERROR:root:In /tmp/sql/instructors.md: Line 88 contains FIXME, indicating work in progress
ERROR:root:In /tmp/sql/instructors.md: Line 92 contains FIXME, indicating work in progress
WARNING:root:In /tmp/sql/index.md: The second element must be a blockquote.
ERROR:root:In /tmp/sql/discussion.md: Line 6 contains FIXME, indicating work in progress
ERROR:root:In /tmp/sql/09-create.md: The document links to reference.html#comma-separated-values, but could not find the anchor comma-separated-values in /tmp/sql/reference.md
ERROR:root:In /tmp/sql/motivation.md: Line 6 contains FIXME, indicating work in progress
ERROR:root:In /tmp/sql/01-select.md: The document links to reference.html#field, but could not find the anchor field in /tmp/sql/reference.md
WARNING:root:Some errors were encountered during validation. See log for details.
```

This works for you?

**Comment by gvwilson** [comment]
Can't test right now - same zip_longest problem you're facing.

**Pull request closed without merging**
