### PR TITLE
Prototype to add next/previous links between topics and other files

### PR DESCRIPTION
**Pull request by rgaiacs**
Since [we aren't going to replace Pandoc with Jekyll this year](http://software-carpentry.org/blog/2015/07/pushing-back.html) this addresses #251.

### CODE REVIEW

**Comment by gvwilson** [comment]
Any implementation of a nav bar in 5.4 depends on a simple, reliable way 
to specify file order...

**Comment by rgaiacs** [comment]
> Any implementation of a nav bar in 5.4 depends on a simple, reliable way to specify file order...

The simple and reliable way is to add fields `previous` and `next` at YAML header of each file. I don't like this solution because will be easy to get links broken and have a script to set the links is almost what I did.

Moreover, Pandoc template engine (if we can call it engine) is very simple and we are limited to `for` and `if-else` clauses.

**Comment by gvwilson** [comment]
Right - so should we delay this until Version 6 (when we switch to 
Jekyll), and somehow hijack page.previous and page.next?

**Comment by rgaiacs** [comment]
> so should we delay this until Version 6 (when we switch to Jekyll)

I don't want to. I think this is our oldest requested feature and not having it is very bad. I'm OK in not spend time having a amazing navigation bar that is always at the top of the page (because browsers compatibility issues) and works nice at any device but not having the navigation bar at the top and bottom of the lessons looks bad for me. Many projects has navigation bar this way (projects with documentation powered by info and Sphinx) so why we don't?

> and somehow hijack page.previous and page.next?

`page.previous` and `page.next` only works for posts as describe [in the documentation](http://jekyllrb.com/docs/variables/).

We can **manually** overwrite `page.previous` and `page.next` adding `previous` and `next` at the YAML header. If we prefer this solution because is Jekyll compatible I'm OK with it since we can change `tools/check.py` to verify that this information are correctly.

**Comment by gvwilson** [comment]
Hi Raniere,
1.  It's not worth putting time into adding features to a system we're 
   going to throw away in six months.
2.  It's definitely not worth disrupting the lessons built on top of the 
   current system only to disrupt them again in a few months.
3.  I think that manually setting prev and next in each document is much 
   clumsier than having one list of page names in _config.yml or the 
   equivalent, so we should figure out how to do the latter in Jekyll and 
   be ready for the switchover in November.

Thanks,
Greg

**Comment by rgaiacs** [comment]
> 1.  I think that manually setting prev and next in each document is much 
>    clumsier than having one list of page names in _config.yml or the 
>    equivalent, so we should figure out how to do the latter in Jekyll and 
>    be ready for the switchover in November.

OK. After November I will revamp https://github.com/gvwilson/using-jekyll/pull/2
to work with a table of content (toc) at `_config.yml`.

**Comment by beroe** [comment]
`<bump>` What is the status of this issue? I agree with the comment above that this is borderline _urgent_.

**Comment by gdevenyi** [comment]
Completely reimplemented here https://github.com/gvwilson/new-lesson-example

**Comment by gvwilson** [comment]
Done with Jekyll Collections.

**Pull request closed without merging**
