### PR TITLE
Adding slides

### PR DESCRIPTION
**Pull request by gvwilson**
Adds templates and example for creating motivational slide deck using [deck.js](http://imakewebthings.com/deck.js/) (which seems a lot cleaner than reveal.js).
- Updating `pages/motivation.md` to use the right template and have the right content.  (Can't avoid using HTML tags for sections...)
- Update `Makefile` to use the right template for the slides (instead of the generic template).
- Create the template for slides.
- Add all the support files needed by `deck.js`.

To do: update `README.md` to describe these changes.

### CODE REVIEW

**Comment by rgaiacs** [comment]
@gvwilson Pandoc has support for revealjs (see [input example](http://johnmacfarlane.net/pandoc/demo/SLIDES) and [output example](http://johnmacfarlane.net/pandoc/demo/example16d.html#/)) and others slides frameworks ([get more information here](http://johnmacfarlane.net/pandoc/README.html#producing-slide-shows-with-pandoc)) but doesn't support deck.js. Did you try this approach?

**Comment by twitwi** [comment]
I don't have much time right now but I can provide support/expertise around deck.js: I use it a lot for my courses and presentation. I also have designed many deck.js extensions (arguably, more than anyone else).

A page with my extensions: http://home.heeere.com/tech-deckjs-ext.html
A recent presentation I made about git: http://twitwi.github.io/Presentation-2014-LaHC-git/

**Comment by gvwilson** [comment]
We used reveal.js in the slides currently in the 'bc' repo - default 
styles were unpleasant to look at, hacking the style to make it less 
ugly was complicated.  deck.js seems to be a better package...

**Comment by gvwilson** [comment]
Congratulations, Rémi, you just volunteered to be our slide expert :-)

**Comment by twitwi** [comment]
:) ok then

**Pull request merged**
