### PR TITLE
Synchronizing gh-pages with core

### PR DESCRIPTION
**Pull request by gvwilson**
Recent changes to `core` should be in `gh-pages`.

### CODE REVIEW

**Comment by abought** [comment]
This is odd: this merged branch would introduce a regression vs master. Even stranger: I can reproduce the regression when merging with a known up-to-date repo.

Specifically: when merged into gh-pages, the validator should pass all unit tests. But it fails `test_missing_colon_at_glossary_definition`, because `check.py` [line 540](https://github.com/swcarpentry/lesson-template/blob/core/tools/check.py#L540) is missing.

I need to run off to a meeting, but will try to trace this divergence later tonight using `git bisect`.

**Comment by abought** [comment]
Ok, now I'm very confused- I've found when the line of code was removed (historically speaking), but the removal of that line doesn't show up in the diff. How is that possible? @r-gaia-cs , any thoughts?

The commit adding the required line WAS added in a mid-December commit. https://github.com/swcarpentry/lesson-template/commit/0b3706702f647e252bd6a7a068c03bd5d717e550

`glossary_keyword = glossary_entry[0]`

It continued to be present until two commits back on gh-pages (Jan 22): 
https://github.com/swcarpentry/lesson-template/blob/c89124ef6ede718e491c658446822b1b7be4a8e3/tools/check.py#L465

It disappeared in the most recent prior merge commit (Jan 26):
https://github.com/swcarpentry/lesson-template/blob/0cda5dd06cf01106eb3332a5d1d36461f1be81a2/tools/check.py

But the removal of the line does not show up in the diff- it's only obvious when inspecting the files.

**Comment by wking** [comment]
On Fri, Feb 06, 2015 at 01:01:21PM -0800, Andy Boughton wrote:

> It disappeared in the most recent prior merge commit (Jan 26):
> https://github.com/swcarpentry/lesson-template/blob/0cda5dd06cf01106eb3332a5d1d36461f1be81a2/tools/check.py
> 
> But the removal of the line does not show up in the diff- it's only
> obvious when inspecting the files.

By default, GitHub renders merge commits by showing the diff between
the merge commit and its first parent (in this case, ae93587).
However, the line in question was removed relative to the _second
parent_ (in this case, dfe4de7).  You can get GitHub to show the diff
by comparing the second parent with the merge commit [1](https://github.com/swcarpentry/lesson-template/compare/swcarpentry:dfe4de7...swcarpentry:0cda5dd#diff-22).

**Comment by abought** [comment]
Thanks, @wking. I'd still like to understand what caused git to go off the rails, at which point I'll whip up a fix and merge this.  Any thoughts? Sorry if I'm making a mountain out of a molehill here.

**Comment by wking** [comment]
On Fri, Feb 06, 2015 at 01:11:21PM -0800, Andy Boughton wrote:

> I'd still like to understand what caused git to go off the rails, at
> which point I'll whip up a fix and merge this.

It looks like it's using 1dc83c75 (Revert "Improve message for
glossary error", 2014-12-19), which is an ancestor of ae93587 but not
dfe4de7.

**Comment by rgaiacs** [comment]
I want to suggest that we close this pull request and open another one merging `core` into `gh-pages` **with** #161. This will solve the problem that @abought reported.

There is another "regression", check https://github.com/r-gaia-cs/swc-lesson-template/tree/test-merge-core,

```
$ python2 tools/test_check.py 2>&1 | tail -n 12
======================================================================
FAIL: test_sample_file_passes_validation (__main__.TestMotivationPage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tools/test_check.py", line 444, in test_sample_file_passes_validation
    self.assertTrue(res)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 55 tests in 0.201s

FAILED (failures=1)
$ python3 tools/test_check.py 2>&1 | tail -n 12                                                                 
======================================================================
FAIL: test_sample_file_passes_validation (__main__.TestMotivationPage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tools/test_check.py", line 444, in test_sample_file_passes_validation
    self.assertTrue(res)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 55 tests in 0.200s

FAILED (failures=1)
```

This is due

```
$ python tools/check.py motivation.md 
ERROR:root:In motivation.md: Document contains heading not specified in the template: Our Mission
ERROR:root:In motivation.md: Document contains heading not specified in the template: The Problem
ERROR:root:In motivation.md: Document contains heading not specified in the template: The Problem
ERROR:root:In motivation.md: Document contains heading not specified in the template: The Problem
ERROR:root:In motivation.md: Document contains heading not specified in the template: Our Solution
ERROR:root:In motivation.md: Document contains heading not specified in the template: Outcomes
ERROR:root:In motivation.md: Document contains heading not specified in the template: Outcomes
ERROR:root:In motivation.md: Document contains heading not specified in the template: The Details
ERROR:root:In motivation.md: Document contains heading not specified in the template: How To Help
ERROR:root:In motivation.md: Document contains heading not specified in the template: Learn More
WARNING:root:Some errors were encountered during validation. See log for details.
```

I'm should be address in another pull request.

**Comment by rgaiacs** [comment]
@abought 

Using the big green button for #161 and #162 and later create one pull request merging `core` into `gh-pages` from GitHub web interface should be enough to solve the problems.

```
$ python tools/test_check.py 2>&1 | tail -n 4
----------------------------------------------------------------------
Ran 55 tests in 0.195s

OK
```

I'm going to sleep now. =)

**Comment by abought** [comment]
Thanks- sounds like the manual fix we discussed was the way to go. Merged those.

 I'm closing this pull request in favor of a more up-to-date merge with core.

**Pull request closed without merging**
