### PR TITLE
Updating CSS based on recent changes to styles repo

### PR DESCRIPTION
**Pull request by gvwilson**
This PR pulls in changes from the master branch of https://github.com/swcarpentry/styles, but does _not_ delete the following files from this repo:
-   `./css/bootstrap/img/`
-   `./css/bootstrap/bootstrap-responsive.css`
-   `./css/lesson.css`
-   `./css/local-fonts`
-   `./css/swc-bootstrap.css`
-   `./css/swc-workshop-and-lesson.css`

Should these be deleted?

### CODE REVIEW

**Comment by fmichonneau** [comment]
Hi @gvwilson, the files you listed should be deleted. Thanks!

**Comment by rgaiacs** [comment]
@gvwilson 

```
$ git rev-parse HEAD
966a0322695852676884f8c094b83d31cc4c728c
$ git checkout -b new-style
Switched to a new branch 'new-style'
$ git rev-parse greg/updating-styles 
f304a56c12e32ee9aafa1aa83d2a36561a9c587f
$ git merge greg/updating-styles 
Auto-merging css/swc.css
CONFLICT (content): Merge conflict in css/swc.css
Auto-merging css/bootstrap/bootstrap.css
Automatic merge failed; fix conflicts and then commit the result.
```

Using

```
$ git checkout --theirs css/swc.css 
$ git add -u
$ git commit
$ make -B preview
```

something bad happen

swc

**Comment by gvwilson** [comment]
Not sure what's gone wrong, but the two key files (swc.css and 
bootstrap.css) are now identical in this pull request and in the 
'master' branch of the 'styles' repo.

**Comment by gdevenyi** [comment]
When this gets updated, do we have a procedure in place to merge these changes into the lesson repos?

**Comment by wking** [comment]
On Wed, Mar 18, 2015 at 08:05:57AM -0700, Gabriel A. Devenyi wrote:

> When this gets updated, do we have a procedure in place to merge
> these changes into the lesson repos?

The current procedure is a push from the center [1](https://github.com/swcarpentry/shell-novice/pull/92#issuecomment-77175753), although
personally I prefer just having lesson maintainers pull core on their
own [2](https://github.com/swcarpentry/shell-novice/pull/92#issuecomment-76765406).

**Comment by gvwilson** [comment]
As soon as the CSS stuff in 'styles' is resolved and merged into the 
'lesson-template' repo, I'll push to the lesson repos.

**Comment by rgaiacs** [comment]
@gvwilson When I try

```
$ make -B preview
```

with

```
$ git log -1
commit 680e7505290c488a9ec950ba4102e5063ff5c51a
Merge: 966a032 e8b726e
Author: Raniere Silva <raniere@ime.unicamp.br>
Date:   Fri Mar 20 18:35:13 2015 -0300

    Merge remote-tracking branch 'swc-styles/master' into merge-style
$ git log HEAD^ -1
commit 966a0322695852676884f8c094b83d31cc4c728c
Merge: 3bc9ec3 07ee109
Author: Raniere Silva <raniere@ime.unicamp.br>
Date:   Mon Mar 2 10:59:58 2015 -0300

    Merge pull request #190 from gvwilson/gh-pages

    Merging core into gh-pages
$ git log HEAD^2 -1
commit e8b726e9ab6ea4736353399d63e15e4e44c03629
Merge: 843999c ec38fb6
Author: Francois Michonneau <francois.michonneau@gmail.Com>
Date:   Mon Mar 2 14:40:09 2015 -0500

    Merge pull request #12 from fmichonneau/site-update

    Update CSS to go with the SWC site template update
```

I still get the bug.

swc

I'm closing this pull request as out of date.

**Pull request closed without merging**
