### PR TITLE
Add more lables to to setup labels script

### PR DESCRIPTION
**Pull request by rgaiacs**
Related with #175.

As soon as #175 was merged I will merge this and update the labels.

### CODE REVIEW

**Comment by abought** [comment]
I was just about to ask about this script... quick work! 

The use of this script doesn't appear to be mentioned in the documentation- should it be?

**Comment by rgaiacs** [comment]
> The use of this script doesn't appear to be mentioned in the documentation- should it be?

I hope that we only need to use this script once for each new lesson and because of this I didn't mention it in any place. If you want I can add something on `README.md`.

**Comment by gvwilson** [comment]
That's a lot of labels - which can we get rid of?

**Comment by gvwilson** [comment]
Please see comments on #175 about which labels we can get rid of, then update this PR.  (Or can this PR and #175 be combined into a single commit?)

**Comment by abought** [comment]
#175 was merged; can you update the tags here to go with it?

**Comment by rgaiacs** [comment]
I update the tags at this repository using the content of this pull request, see https://github.com/swcarpentry/lesson-template/labels. I'm going to merge this and update the others repositories.

**Pull request merged**
