### PR TITLE
Add navigation links

### PR DESCRIPTION
**Pull request by rgaiacs**
**This is a hack using bash script to get the next and previous lesson.**

Sample:

swc

TODO: improve CSS.

### CODE REVIEW

**Comment by gvwilson** [comment]
Thanks for this, but it's a low-priority issue for now - validating 
workshops and lessons has to take precedence.

**Comment by aaren** [comment]
If there are going to be lots of things like this that would have been easy to do in Jekyll then maybe it's worth considering the [Jekyll Pandoc](https://github.com/mfenner/jekyll-pandoc) plugin that allows you to use pandoc as the markdown converter in a Jekyll site.

I'm using this plugin on one of my projects and it is pretty simple. The difference here would be copying the contents of `_site` to the root dir.

**Comment by gvwilson** [comment]
Closing this: if we're going to do it, let's do it right (but later).

**Comment by amueller** [comment]
is there any open issue tracking this? I feel this is a major issue in navigating the site. I'm happy to have a look if it helps.

**Comment by gvwilson** [comment]
We have an overhaul of our template in the wings - once that's in, we'd 
like to address fwd/back (and other aspects of navigation).  If you'd 
like to help land it, please mail me (gvwilson @ software-carpetry.org).
Thanks,
Greg

**Comment by rgaiacs** [comment]
> We have an overhaul of our template in the wings - once that's in, we'd 
> like to address fwd/back (and other aspects of navigation).  If you'd 
> like to help land it, please mail me (gvwilson @ software-carpetry.org).

@gvwilson Any reason to keep this discussion in private?

**Comment by gvwilson** [comment]
Wasn't aware it was private?

**Comment by rgaiacs** [comment]
> Wasn't aware it was private?

I know that you sometimes want to low the traffic on GitHub issues
but since more than half a dozen instructors complain about this on GitHub
and many others when I talk with them I really prefer that you keep this
conversation here (in public) instead of on your email inbox. =)

**Pull request closed without merging**
