### PR TITLE
Update examples for use revealjs type

### PR DESCRIPTION
**Pull request by rgaiacs**
**Based on changes of #128. Only merge after #128 be merged and `core` be merged into `gh-pages`.**

### CODE REVIEW

**Comment by gvwilson** [comment]
No - we are using deck.js, not reveal.js.

**Comment by rgaiacs** [comment]
For more information about this please check https://github.com/swcarpentry/lesson-template/pull/128#issuecomment-70426726.

**Comment by twitwi** [comment]
This looks ok to me, given what I've done in https://github.com/twitwi/lesson-template/tree/core-deckjs

Depending on how much we want to put in the template motivation.md file, see also https://github.com/swcarpentry/lesson-template/issues/60

**Comment by rgaiacs** [comment]
I'm closing this and will let @twitwi handle this at #60.

**Pull request closed without merging**
