### PR TITLE
Add documentation for writing lessons in R Markdown.

### LINKED ISSUE #149: Need documentation for creating R lesson
The current documentation does not provide instruction on how to create an R lesson. We write the lessons in R Markdown, and then convert to Markdown version that conforms to the lesson template standards by sourcing the settings in tools/chunk-options.R. Also, the Makefile already incorporates the conversion from R Markdown to Markdown.

Where would be a good location for me to add this information?

### PR DESCRIPTION
**Pull request by jdblischak**
Fixes #149. Feedback appreciated.

### CODE REVIEW

**Comment by fmichonneau** [comment]
Great job distilling these recommendations for the R lessons!

**Comment by naupaka** [comment]
Looks good to me too. :thumbsup:

**Comment by jdblischak** [comment]
Thanks for looking it over, @fmichonneau and @naupaka.

@r-gaia-cs or @gvwilson, please merge if the formatting looks good.

**Comment by rgaiacs** [comment]
@jdblischak Thanks a lot for this. It looks great.

**Pull request merged**
