### PR TITLE
Add requirements.txt

### PR DESCRIPTION
**Pull request by abought**
We should track dependencies to ease setup.

Tested this requirements.txt file using a clean virtualenv, python2. Successfully ran both the validator/unit tests and the lesson build process (`make preview`).

### CODE REVIEW

**Comment by rgaiacs** [comment]
@abought Thanks for the pull request.

Could you add some information in `README.md`?

And if you don't mind, could you also squash the commits?

**Comment by abought** [comment]
Thanks for the feedback. Changing README.md is going to require merging into `gh-pages` instead of `core`... I will open a new pull request accordingly.

This system of two equivalent and overlapping masters is complicated, sometimes...

**Comment by gvwilson** [comment]
> This system of two equivalent and overlapping masters is complicated, 
> sometimes...
> Yup - but I think the complexity on our side makes things simpler for 
> the average author.  We'll know by February...

Cheers,
Greg

**Comment by rgaiacs** [comment]
> Changing README.md is going to require merging into gh-pages instead of core... I will open a new pull request accordingly.

I'm still forgetting of `core` vs `gh-pages`. The workflow that I prefer is send a pull request to `core` and another to `gh-pages` (this one making clear that is should only be merge after `core` be merged).

**Comment by gvwilson** [comment]
How about sending to core with a note to merge to gh-pages after the 
merge to core?

**Comment by abought** [comment]
There is no README.md on `core`, so my primitive git fu didn't allow a straight merge. (one changed file shared on both branches + changes to a file that doesn't exist on `core`)

I've created a separate pull request for `core` (to which I independently added requirements.txt).

So much for the "quick and easy" commit to get me back up to speed!

**Pull request closed without merging**
