### PR TITLE
Move lesson-template docs to doc/template

### PR DESCRIPTION
**Pull request by wking**
Re-opening #124 against gh-pages now that we've shifted the old
gh-pages off to swcarpentry/lesson-example and renamed this
repository's old core to gh-pages.

### CODE REVIEW

**Comment by gvwilson** [comment]
I'm -1 on pushing the docs into a sub-directory.

**Comment by wking** [comment]
On Sat, Apr 04, 2015 at 12:29:17PM -0700, Greg Wilson wrote:

> I'm -1 on pushing the docs into a sub-directory.

Can you explain why?  I think it's good to have the docs for the
template content available in the template repository (and not
externalized in lesson-example and then blown away after the
downstream lesson is created).  See my opening comment in #124 for
more detail on this line.  And I don't see a downside (but that
doesn't mean there aren't any ;).

**Comment by rgaiacs** [comment]
> I think it's good to have the docs for the
> template content available in the template repository (and not
> externalized in lesson-example and then blown away after the
> downstream lesson is created).

I normally prefer to have a directory called `doc` side-by-side with `src` (or the name you must use to it) but in this case I prefer to have `doc` at `lesson-example` since will make easy for people play with it.

**Comment by wking** [comment]
On Tue, Apr 07, 2015 at 07:14:12AM -0700, Raniere Silva wrote:

> > I think it's good to have the docs for the
> > template content available in the template repository (and not
> > externalized in lesson-example and then blown away after the
> > downstream lesson is created).
> 
> I normally prefer to have a directory called `doc` side-by-side with
> `src` (or the name you must use to it) but in this case I prefer to
> have `doc` at `lesson-example` since will make easy for people play
> with it.

If the _source_ for the docs is lesson-example, those docs will go
stale in downstream lessons as maintainers continue to pull from
lesson-template without receiving doc updates.  If the source for the
docs is lesson-template, then both lesson-examples and other
downstream lessons will always have the docs matching their version of
the template.

**Comment by gvwilson** [comment]
Let's leave things as they are until August, then get feedback from 
lesson authors about what they're finding easy vs. confusing.

**Comment by wking** [comment]
On Tue, Apr 07, 2015 at 03:13:57PM -0700, Greg Wilson wrote:

> Let's leave things as they are until August, then get feedback from
> lesson authors about what they're finding easy vs. confusing.

This idea has been cooking for almost three months already, so I'm
clearly not in rush ;).  Where should we collect new docs until we
have time to decide?  Or does “leave things as they are” mean “no new
lesson-template/lesson-example docs”?  For example, I need to
understand where you think wking/swc-lesson-template#1 should live.

**Comment by gvwilson** [comment]
Has gone stale.

**Comment by wking** [comment]
On Fri, Jun 17, 2016 at 04:07:21AM -0700, Greg Wilson wrote:

> Has gone stale.

I still think having docs in the same repository is a good idea, and
am happy to reroll if there is interest from the template maintainers.

**Comment by gvwilson** [comment]
What do you think of the docs in 
https://swcarpentry.github.io/lesson-example/ ?

**Comment by wking** [comment]
On Fri, Jun 17, 2016 at 09:18:15AM -0700, Greg Wilson wrote:

> What do you think of the docs in 
> https://swcarpentry.github.io/lesson-example/ ?

They're great, but I think there's a useful distinction between:
- An example/seed repository (for which lesson-example is a great fit)
  and
- Documentation on using the template (which I think should go in the
  template repository).

Splitting things like that would give lesson maintainers a local copy
of the “how to use the template” docs that updates when they pull new
versions of the template.

**Pull request closed without merging**
