### PR TITLE
Use revealjs type for motivation.md

### PR DESCRIPTION
**Pull request by rgaiacs**
**Duplicate of  #127 to fix correct branch**.

Pandoc has `revealjs` as output format. Using it allows us to avoid HTML in `motivation.md`.

### CODE REVIEW

**Comment by rgaiacs** [comment]
@twitwi Could you review this?

**Comment by rgaiacs** [comment]
Long explanation that I send to @gvwilson in private email:

```
I suggest the change because

    $ pandoc -t html <<EOF
    ## Foo
    EOF                                                                   
    <h2 id="foo">Foo</h2>
    $ pandoc -t revealjs <<EOF
    ## Foo
    EOF
    <section>
    <section id="foo" class="titleslide slide level2">
    <h1>Foo</h1>
    </section>
    </section>

what means that we will avoid HTML at `motivation.md`.

Since we are calling Pandoc with our own template we will get `motivation.html`
using deck.js as we want and not reveal.js.

This is based on
https://github.com/jgm/pandoc/issues/1753#issuecomment-62649327.
```

Hope this makes things clear.

**Comment by twitwi** [comment]
A priori, it should not be too bad by default, I'll have a look now.

@gvwilson if you read this, I'll rebase that at the same time: https://github.com/swcarpentry/lesson-template/issues/60

**Comment by twitwi** [comment]
Status report:
- (I lost some time because I didn't know about core vs gh-pages)
- it seems to globally work
- but there are still problems, at least with a few slides
- I need to dig more
- I'll do it later

**Comment by twitwi** [comment]
The commit from this PR has been cherry picked together with a big rebase/rewrite of https://github.com/swcarpentry/lesson-template/issues/60 in: https://github.com/twitwi/lesson-template/tree/core-deckjs

Live demo: http://twitwi.github.io/lesson-template/motivation

Markdown source of this demo (gh-pages branch): https://github.com/twitwi/lesson-template/tree/gh-pages

I think we should close this and keep track of things using: https://github.com/swcarpentry/lesson-template/issues/60 ... please close if you agree.

**Pull request closed without merging**
