### PR TITLE
Adding missing CSS files.

### LINKED ISSUE #11: Missing CSS files
```
    <link rel="stylesheet" href="css/bootstrap/bootstrap.css" />
    <link rel="stylesheet" href="css/bootstrap/bootstrap-responsive.css" />
    <link rel="stylesheet" type="text/css" href="swc-bootstrap.css" />
```

### PR DESCRIPTION
**Pull request by gvwilson**
1. Bringing in Bootstrap CSS files.
2. Merging swc.css and swc-bootstrap.css from 'bc' repository.
3. Updating _includes/header.html to refer to the right files.

Closes #11.

### CODE REVIEW

**Comment by rgaiacs** [comment]
Do we want things from our main web site in this CSS? E.g

```
/* Person's name in team.html. */
span.person {
 font-weight: bold;
 font-style: italic;
}

/* Bibliography book covers. */
img.book-cover {
 width: 80px;
}

/* Blog calendar table in blog/index.html. */
table.blogcalendar th {
 text-align : right;
 font-weight : bold;
}
```

**Comment by gvwilson** [comment]
Nope.

**Comment by rgaiacs** [comment]
@gvwilson The HTML is missing some elements and class and the CSS doesn't apply correctly.

swc

Any comment?

**Comment by gvwilson** [comment]
It probably needs to be fixed. :-)

**Pull request merged**
