### PR TITLE
Move lesson-template docs to doc/template

### PR DESCRIPTION
**Pull request by wking**
We don't want them cluttering lesson repositories or creating merge
conflicts (e.g. if the README.md is adjusted in both core and the
downstream lesson).  However, we do want the docs in the core branch
(so we can land changes along with their docs).  Shifting these to a
subdirectory gives us a way to keep the docs in core while still
making them easy to ignore (or remove) if downstream lesson authors
aren't interested in them.

All but the last two commits just cherry-pick changes from gh-pages.
The docs were originaly removed from core in 3eaab25 (Removing example
files), so I looked at what had changed:

```
$ git log --graph --topo-order --oneline --decorate 3eaab25^..origin/gh-pages -- README.md LAYOUT.md FAQ.md DESIGN.md
* 25b664b (origin/gh-pages, origin/HEAD) Minor grammatical fixes to FAQ and LAYOUT
* 37549a6 (origin/pr/117) Add input cell question to FAQ and LAYOUT
* 72a3c02 (origin/pr/101) Fix capitalization per gvw
* bca3ae6 (origin/pr/100) Add requirements.txt necessary to build lessons and run validator.
*   a250864 Merge pull request #95 from aaren/fix-readme-pandoc-link
|\
| * ed5d14c (origin/pr/95) readme: link to new pandoc.org website
* |   58b9f13 Merge branch 'gh-pages' of github.com:swcarpentry/lesson-template into gh-pages
|\ \
| * | dc9eaa5 (origin/pr/92) Add information about problems with Pandoc to FAQ
| |/
* | 9220a1d Fixing double 'out' typo
|/
* 317a7c3 (origin/pr/80) Merging changes from master
* 1c096c7 Telling people to point back to this site
* 068cb3a (origin/pr/71) Explaining the new label
```

Created a new branch with:

```
$ git checkout -b docs 3eaab25^
```

And copied over the changes (removing the autogenerated HTML forms):

```
$ git cherry-pick 068cb3a 1c096c7 317a7c3 9220a1d dc9eaa5 ed5d14c bca3ae6 72a3c02 37549a6 25b664b
$ git rm LAYOUT.html
$ git cherry-pick --continue
$ git rm index.html
$ git cherry-pick --continue
$ git rm FAQ.html
$ git cherry-pick --continue
```

### CODE REVIEW

**Comment by wking** [comment]
This is still a work in progress.  I'm testing with:

```
#!/bin/sh

rm -rf template lesson &&
git clone git://github.com/wking/swc-lesson-template.git template &&
(
    cd template &&
    git checkout core &&
    git merge origin/docs &&
    git checkout gh-pages &&
    git merge core
) &&
git clone template lesson &&
(
    cd lesson &&
    git checkout gh-pages &&
    echo 'My README' > README.md
) &&
(
    cd template &&
    git checkout core &&
    echo 'more notes' >> doc/template/README.md &&
    git commit -am 'More README notes'
) &&
(
    cd lesson &&
    git pull origin core  # no conflicts :)
)
```

but it looks like I need to deal with `index.md` and `motivation.md` too (removed in core, but present in my branch).

**Comment by rgaiacs** [comment]
I talk with @wking on IRC and I will continue the work on this so he can focus on amy.

**Comment by wking** [comment]
Instead of building this on top of 3eaab25^, we can probably avoid the
conflicts with index.md, etc., by starting with 3eaab25 itself:

  $ git checkout -b docs 3eaab25

Then create an alternative version that doesn't delete the stuff we
want (but still deletes index.md, etc.:

  $ git checkout HEAD^ -- README.md LAYOUT.md FAQ.md DESIGN.md
  $ git commit --amend --no-edit

Then continue as before:

  $ git cherry-pick 068cb3a 1c096c7 317a7c3 9220a1d dc9eaa5 ed5d14c bca3ae6 72a3c02 37549a6 25b664b
  …

I've pushed the revised branch, and now my checks pass with:

  #!/bin/sh

  rm -rf template lesson &&
  git clone git://github.com/wking/swc-lesson-template.git template &&
  (
    cd template &&
    git checkout core &&
    git merge origin/docs  # this fails with merge conflicts
    cat >requirements.txt <<-EOF
        CommonMark
        pandocfilters
        PyYAML
        EOF
    git add README.md requirements.txt doc/template &&
    git commit -m "Merge remote-tracking branch 'origin/docs' into core" &&
    git checkout gh-pages &&
    git merge core  # this fails with merge conflicts
    git checkout core -- README.md &&
    git commit -m "Merge branch 'core' into gh-pages"
  ) &&
  git clone template lesson &&
  (
    cd lesson &&
    git checkout gh-pages &&
    echo 'My README' > README.md
  ) &&
  (
    cd template &&
    git checkout core &&
    echo 'more notes' >> doc/template/README.md &&
    git commit -am 'More README notes'
  ) &&
  (
    cd lesson &&
    git pull origin core  # no conflicts :)
  )

Lessons based on the current gh-pages branch will likely need the same
initial conflict resolution I'm using here for my local template's
gh-pages, but after that we won'd have any README.md conflicts (as you
can see by the final pull succeeding).

**Comment by wking** [comment]
Looking at the merge conflicts more closely:

On Sat, Jan 17, 2015 at 08:21:25AM -0800, W. Trevor King wrote:

> ```
>   git merge origin/docs  # this fails with merge conflicts
>   cat >requirements.txt <<-EOF
>       CommonMark
>       pandocfilters
>       PyYAML
>       EOF
>   git add README.md requirements.txt doc/template &&
>   git commit -m "Merge remote-tracking branch 'origin/docs' into core" &&
> ```

The README.md and doc/template conflicts are unavoidable, since those
files had been removed in the core branch, and our goal is to add the
versions from docs.  The requirements.txt conflict is because my docs
branch doesn't have some requirements.txt updates.  You could also
resolve it with:

  $ git checkout HEAD -- requirements.txt

> ```
>   git checkout gh-pages &&
>   git merge core  # this fails with merge conflicts
>   git checkout core -- README.md &&
>   git commit -m "Merge branch 'core' into gh-pages"
> ```

This conclict is apparently unavoidable.  I'd expect Git to notice
that the gh-pages README.md matched the one docs moved to
doc/template/, but it doesn't seem to.  Still, it's an easy, one-off
resolution.

Also, gh-pages has advanced the docs since my initial survey.  A new
list of cherry-pick commits would include:

  $ git log --graph --topo-order --oneline --decorate 3eaab25^..origin/gh-pages -- README.md LAYOUT.md FAQ.md DESIGN.md
- a5fbf82 (origin/pr/125) Update LAYOUT for changes from #103
- f292d66 (origin/pr/122) Add classes
- 25b664b Minor grammatical fixes to FAQ and LAYOUT
  …

I'll leave off redoing my branch again until we accept or reject this
approach, since there's no benefit in trying to keep up until we
decide if this is the way we want to handle things.

**Pull request closed without merging**
