### PR TITLE
Merging CSS from styles repository

### PR DESCRIPTION
**Pull request by gvwilson**
This seems to have a lot more in it than I expected...

### CODE REVIEW

**Comment by fmichonneau** [comment]
yes, it looks right. Raniere imported the history using the css from the website. That's why it looks so large.

Thanks!

**Comment by gvwilson** [comment]
Gotcha - please go ahead and merge if it looks good to you.
- G

On 2015-02-03 11:57 AM, Francois Michonneau wrote:

> yes, it looks right. Raniere imported the history using the css from 
> the website. That's why it looks so large.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/lesson-template/pull/153#issuecomment-72688439.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by fmichonneau** [comment]
It works in the sense that the new files got imported, and the files for which the content changed got updated, but the old files that should be deleted are still there. How should we proceed? Should I create a PR against this repo that removes the unneeded files? Or should we delete the css folder and reimport the css folder from styles?

**Comment by gvwilson** [comment]
If you can send me the list of files that should be deleted, I'll do 
that and refresh the PR.  Apologies for not tracking this more carefully...
Thanks,
Greg

On 2015-02-03 12:28 PM, Francois Michonneau wrote:

> It works in the sense that the new files got imported, and the files 
> for which the content changed got updated, but the old files that 
> should be deleted are still there. How should we proceed? Should I 
> create a PR against this repo that removes the unneeded files? Or 
> should we delete the css folder and reimport the css folder from styles?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/lesson-template/pull/153#issuecomment-72694789.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by fmichonneau** [comment]
These files and folders need to be removed:
- css/bootstrap/img/
- css/bootstrap/bootstrap-responsive.css
- css/lesson.css
- css/swc-bootstrap.css
- css/swc-workshop-and-lesson.css
- css/local-fonts/

Thanks Greg!

**Comment by gvwilson** [comment]
Thanks @fmichonneau - please re-check?  If it looks good, please go 
ahead and merge.

**Comment by fmichonneau** [comment]
check http://swcarpentry.github.io/lesson-template/ but I think the button-links look OK. Please open an issue if something doesn't look right to you. Thanks!

**Comment by gvwilson** [comment]
Yup, looks good now - thanks.

**Pull request merged**
