### PR TITLE
Clean CSS file

### PR DESCRIPTION
**Pull request by rgaiacs**
Following #12, this PR cleans css/swc.css by removing dead code (e.g. style from Software Carpentry homepage).

### CODE REVIEW

**Comment by rgaiacs** [comment]
@acabunoc If you aren't very busy with Mozilla Science stuffs could you check that I didn't remove something important by accident?

**Comment by gvwilson** [comment]
If it renders, it's good enough for me :-)

**Comment by rgaiacs** [comment]
Need some improve at CSS margin/padding/border but it renders.

swc

**Comment by abbycabs** [comment]
@r-gaia-cs took a quick look, I think this is good :+1:

**Pull request merged**
