### PR TITLE
add very-clean target to makefile

### PR DESCRIPTION
**Pull request by aaren**
This allows us to delete the generated html.

### CODE REVIEW

**Comment by gvwilson** [comment]
Mm... I'm nervous about this, because the _only_ time we'll want to do 
this is in this repo - everything that inherits from it for creating an 
actual lesson will really, really not want an easy way to delete the 
generated HTML pages.

**Comment by aaren** [comment]
Shouldn't they be saved it git anyway? How about an 'are you sure?' prompt?

**Comment by gvwilson** [comment]
Yes, they should be saved in Git, but is there a use case for this 
target other than in the starting-point repository?

**Comment by aaren** [comment]
When I was testing my filter, make wouldn't regenerate the pages because the inputs weren't changing, even though the filter had. 

I can see that this shouldn't be a problem for a user though and perhaps it is best not to make this too easy to do.

**Pull request closed without merging**
