### PR TITLE
Manage per-file copyright blurbs with update-copyright

### PR DESCRIPTION
**Pull request by wking**
As an optional extension to #197, we can use the update-copyright.py
script to maintain per-file contributor lists and copyright blurbs in
our source files.  For now, I've just done this with tools/check.py,
but it's easy to manage the blurb in any file that uses hash comments;
just add a ‘# Copyright’ line where you want the blurb, and
update-copyright.py will fill it in for you.  Do we want this, or are
we just sticking to a global author list and no copyright blurbs?

### CODE REVIEW

**Comment by fmichonneau** [comment]
I noticed that this PR affects CSS files that are out of date. For instance swc-bootstrap.css doesn't exist anymore. I'm still confused on the workflow between core and gh-pages, but it looks like the changes to the css folder from gh-pages need to be merged into core.

**Comment by wking** [comment]
On Thu, Mar 12, 2015 at 01:12:42PM -0700, Francois Michonneau wrote:

> I noticed that this PR affects CSS files that are out of date. For
> instance swc-bootstrap.css doesn't exist anymore. I'm still confused
> on the workflow between core and gh-pages, but it looks like the
> changes to the css folder from gh-pages need to be merged into core.

gh-pages is downstream of core (see [1](https://github.com/swcarpentry/lesson-template/issues/118#issuecomment-70260155)), so we don't want to merge it
into core.  The idea is that changes that you want to push downstream
into _existing_ lessons should be submitted against core, and changes
that only effect _new_ lessons (e.g. tweaking an example template)
should be submitted against gh-pages.  I'd expect CSS changes would
always fall into the former category, and so should always be
submitted against the core branch.

**Comment by fmichonneau** [comment]
OK, thanks for the clarification @wking! In this case, it means that we need to bring the css changes into core as well.

**Comment by gvwilson** [comment]
Can someone tell me what CSS files need to be brought into core?  Can I do it by merging the 'styles' repo into the 'core' branch of this one?

**Comment by fmichonneau** [comment]
Yes, merging the content of the styles repo into core should work. In other
words replacing the full content of this css folder with the content of the
css folder from styles.

**Comment by gvwilson** [comment]
@fmichonneau please see 
https://github.com/swcarpentry/lesson-template/pull/200

**Comment by fmichonneau** [comment]
This PR looks good now that the CSS files have been updated.

**Pull request closed without merging**
