### PR TITLE
Core and gh-pages aren't sync

### PR DESCRIPTION
**Pull request by rgaiacs**
Some changes at `core` files are only available at `gh-pages`.

What I did was, more or less,

```
$ git diff --name-only gh-pages > /tmp/files
```

Remove
- `css/bootstrap/bootstrap-responsive.css`
- `css/bootstrap/img/glyphicons-halflings-white.png`
- `css/bootstrap/img/glyphicons-halflings.png`
- `css/lesson.css`
- `css/local-fonts/zhcz-_WihjSQC0oHJ9TCYBsxEYwM7FgeyaSgU71cLG0.woff`
- `css/swc-bootstrap.css`
- `css/swc-workshop-and-lesson.css`

from `/tmp/files` since this files no longer exist in `gh-pages`.

```
$ git rm css/bootstrap/bootstrap-responsive.css css/bootstrap/img/glyphicons-halflings-white.png css/bootstrap/imgoHJ9TCYBsxEYwM7FgeyaSgU71cLG0.woff css/swc-bootstrap.css css/swc-workshop-and-lesson.css
$ git checkout gh-pages -- $(cat /tmp/files)
$ git commit
```

@gvwilson Can you review and merge this as soon as possible. And also merge `core` to the lessons?

@wking Just as curiosity, there was a easy way to do what I did?

### CODE REVIEW

**Comment by wking** [comment]
On Wed, Mar 18, 2015 at 08:47:45PM -0700, Raniere Silva wrote:

> Some changes at `core` files are only available at `gh-pages`.

This overlaps at least partly with #200.  You should compare the two
tips and see if #200 needs adjusting, since it's better to pull from
swcarpentry/styles than to cut/paste from gh-pages.  For example,
bootstrap-responsive.css was removed upstream in
swcarpentry/styles@7d6cd0d (upgrade to bootstrap 3.3.2, 2015-01-27)
and is reflected in #200.

**Comment by gvwilson** [comment]
Hi,
I'm unlikely to be able to go through this in the next 24 hours, so if 
@r-gaia-cs and @wking are happy, and @fmichonneau believes these are the 
right files, please go ahead and merge.
Thanks,
@gvwilson

**Comment by wking** [comment]
On Thu, Mar 19, 2015 at 09:35:03AM -0700, Greg Wilson wrote:

> I'm unlikely to be able to go through this in the next 24 hours, so
> if @r-gaia-cs and @wking are happy, and @fmichonneau believes these
> are the right files, please go ahead and merge.

I'd rather merge #200 first, since merging from swcarpentry/styles is
how this content is supposed to get updated.  However, #200 still has
issues (as far as I know) [1](https://github.com/swcarpentry/lesson-template/pull/200#issuecomment-82541222).

**Comment by rgaiacs** [comment]
swc

This doesn't have the CSS problem from #200.

**Comment by rgaiacs** [comment]
I will merge this to avoid the problem that @ChristinaLK had and be more careful when merging changes from https://github.com/swcarpentry/styles/.

**Pull request merged**
