### PR TITLE
Add MathJax

### LINKED ISSUE #285: Rendering LaTeX equations in R Markdown files
One nice feature of R Markdown is that it will render LaTeX equations ([syntax](http://rmarkdown.rstudio.com/authoring_basics.html)). We have a [PR](https://github.com/swcarpentry/r-novice-inflammation/pull/154) from @michaellevy to [r-novice-inflammation](https://github.com/swcarpentry/r-novice-inflammation) which includes a demonstration of this feature. However, the equation does not render properly when using our pandoc-based workflow. Would it be possible to update this to accommodate this feature?

When converting Markdown to HTML, the [rmarkdown](http://rmarkdown.rstudio.com) package uses the following pandoc flags:

```
 --to html
 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures
 --output 07-knitr-R.html
 --smart
 --email-obfuscation none
 --self-contained
 --standalone
 --section-divs
 --template /usr/lib/R/site-library/rmarkdown/rmd/h/default.html
 --variable 'theme:bootstrap'
 --include-in-header /tmp/RtmpgXmbe8/rmarkdown-strdb9256d2983.html
 --mathjax
 --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
 --no-highlight
 --variable highlightjs=/usr/lib/R/site-library/rmarkdown/rmd/h/highlight 
```

I tried updating the pandoc args in the lesson-template Makefile to include the flags that are likely involved in facilitating this, but it didn't work:

```
PANDOC_FLAGS = --smart --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures
```

### PR DESCRIPTION
**Pull request by rgaiacs**
Close #285 and #121.

### CODE REVIEW

**Comment by jdblischak** [comment]
+1 to merge

**Comment by twitwi** [comment]
I'm late to the discussion (I just discovered it to be frank) so please excuse me for commenting on a merge PR. I want to comment here to keep a record for future discussions.

I've been using latex-syntax for math equations in my html slides for some time (I'd rather not count the years :) ). Here is my current view on this:
- mathml isn't sufficiently supported [0], still even today...
- mathjax is ok but will cause issues if we want to go offline (it can become huge),
- I had used a tiny jsscript [1] that was partially working but had issues with time [2],
- I now switched to katex [3], which is active, small and works well [4]
- If we want to go offline at some point in the future, I'd recommend katex as it's the best compromise 

[0] http://caniuse.com/#search=mathml
[1] which was named "display-latex2.user.js"
[2] http://home.heeere.com/data/deck-js-demo-2/samples/deck-simplemath.html#slide-2
[3] http://khan.github.io/KaTeX/
[4] http://twitwi.github.io/Presentation-2016-02-11-Sparsity-Day/presentation-2.html#slide-13

**Comment by rgaiacs** [comment]
@twitwi Thanks for the comments.

About [KaTeX](http://khan.github.io/KaTeX/), I only check it when it was launch. At that time KaTeX was fast than MathJax for "common" math but doesn't have many LaTeX commands (maybe it doesn't support matrix at that time?).

**Comment by twitwi** [comment]
That's very probable, it made a lot of progress in the last months. We'll recheck it when/if the offline issue comes in.

**Pull request merged**
